SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE 
from BOOK join AUTHOR
on BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
where category = '경제'
order by PUBLISHED_DATE;